server: &server
  adapter: postgresql
  pool: 5
  min_messages: WARNING
  host: localhost

development:
  adapter: postgresql
  pool: 5
  min_messages: WARNING
  host: localhost

development:
  <<: *server
  database: cat_dev

test:
  <<: *server
  database: cat_test

production:
  <<: *server
  database: cat_prod
